import type { Preset, PresetId, Finish, FinishId } from "./types";

export const PRESET_BY_ID: Readonly<Record<PresetId, Preset>> = {
  standard: {
    id: "standard",
    name: "Standard",
    subtitle: "Pure engineering",
    specs: { acceleration: 2.8, speed: 320, range: 280, weight: 600 },
    height: 0,
    dashboard: 1,
    armor: 0,
    equipment: 0,
    wheelbase: 0,
    rideHeightMm: 145,
    features: {
      stabilizers: false,
      grapple: false,
      spoiler: false,
      thrusters: false,
      cannons: false,
      turret: false,
      missilePod: false,
      launchers: false,
      headlights: false,
    },
  },
  tactical: {
    id: "tactical",
    name: "Tactical Mode",
    subtitle: "Always prepared",
    specs: { acceleration: 3.1, speed: 290, range: 310, weight: 655 },
    height: 0.18,
    dashboard: 1,
    armor: 0.03,
    equipment: 0.08,
    wheelbase: 0,
    rideHeightMm: 200,
    features: {
      stabilizers: true,
      grapple: true,
      spoiler: false,
      thrusters: false,
      cannons: false,
      turret: false,
      missilePod: false,
      launchers: false,
      headlights: true,
    },
  },
  pursuit: {
    id: "pursuit",
    name: "Pursuit Mode",
    subtitle: "Uncompromising pace",
    specs: { acceleration: 2.4, speed: 355, range: 240, weight: 560 },
    height: -0.18,
    dashboard: 0.58,
    armor: -0.05,
    equipment: 0,
    wheelbase: 0.2,
    rideHeightMm: 90,
    features: {
      stabilizers: false,
      grapple: false,
      spoiler: true,
      thrusters: true,
      cannons: false,
      turret: false,
      missilePod: false,
      launchers: false,
      headlights: false,
    },
  },
  combat: {
    id: "combat",
    name: "Combat Mode",
    subtitle: "Maximum protection",
    specs: { acceleration: 3.3, speed: 300, range: 250, weight: 690 },
    height: 0.08,
    dashboard: 1,
    armor: 0.08,
    equipment: 0.14,
    wheelbase: 0,
    rideHeightMm: 170,
    features: {
      stabilizers: false,
      grapple: false,
      spoiler: false,
      thrusters: false,
      cannons: true,
      turret: true,
      missilePod: true,
      launchers: true,
      headlights: true,
    },
  },
};
export const PRESETS: readonly Preset[] = Object.values(PRESET_BY_ID);
export const FINISH_BY_ID: Readonly<Record<FinishId, Finish>> = {
  black: {
    id: "black",
    name: "Stealth Black",
    color: "#343940",
    roughness: 0.46,
    metalness: 0.5,
  },
  graphite: {
    id: "graphite",
    name: "Graphite Gray",
    color: "#545f65",
    roughness: 0.32,
    metalness: 0.8,
  },
  silver: {
    id: "silver",
    name: "Titanium Silver",
    color: "#a7b4bd",
    roughness: 0.25,
    metalness: 0.85,
  },
};
export const FINISHES: readonly Finish[] = Object.values(FINISH_BY_ID);
